import LogoLink from './components/LogoLink'
import NavbarApiButton from './components/NavbarApiButton'

export default {
  logo: <LogoLink />,
  project: {
    link: 'https://github.com/Jolli-sample-repos/phu-site-3',
  },
  docsRepositoryBase: 'https://github.com/Jolli-sample-repos/phu-site-3',
  editLink: {
    component: null,
  },
  feedback: {
    content: null,
  },
  sidebar: {
    defaultMenuCollapseLevel: 2,
  },
  toc: {
    title: 'On This Page',
  },
  head: (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta property="og:title" content="phu new site" />
      <meta property="og:description" content="Documentation for phu new site" />
      <style>{`:root { --nextra-primary-hue: 212deg; }`}</style>
    </>
  ),
  darkMode: true,
  nextThemes: {
    defaultTheme: 'system',
  },
  navbar: {
    extraContent: <NavbarApiButton />,
  },
  footer: {
    text: 'phu new site · Generated by Jolli',
  },
  useNextSeoProps() {
    return {
      titleTemplate: '%s – phu new site'
    }
  }
}
